image: continuumio/miniconda3:latest

testbuild :
  stage: build
  script:
    - conda create --file requirements.yaml
    - source activate plugy
    - python -m unittest
    - python setup.py install
